name: beacon_share
description: A utility application to securely share your live location with your friends.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_dynamic_links: ^0.5.0+11
  url_launcher: ^5.4.2
  modal_progress_hud: ^0.1.3
  fluttertoast: ^3.1.3
  firebase_core: ^0.4.2+1
  cloud_firestore: ^0.13.4+2
  geolocator: ^5.1.4+2
  google_maps_flutter: ^0.5.24+1
  flutter_time_picker_spinner: ^1.0.6
  intl: ^0.16.1
  flutter_duration_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/futura_bold.otf